services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=0.0.0.0
      - RUNNING_AT_HOST=0.0.0.0
      - RUNNING_AT_PORT=8080
  redis:
    image: "redis:latest"
    ports:
      - "6400:6379"
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  app-network:
    driver: bridge