services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=0.0.0.0
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network
  
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge